class Absence < ApplicationRecord
  belongs_to :volunteer
  belongs_to :absence
  belongs_to :volunteer
  belongs_to :region
  belongs_to :region
  belongs_to :region
  belongs_to :log
  belongs_to :food_type
  belongs_to :log
  belongs_to :log
  belongs_to :volunteer
  belongs_to :donor
  belongs_to :transport_type
  belongs_to :region
  belongs_to :scale_type
  belongs_to :schedule_chain
  belongs_to :tax
  belongs_to :region
  belongs_to :transport_type
  belongs_to :scale_type
  belongs_to :region
  belongs_to :schedule
  belongs_to :food_type
  belongs_to :volunteer
  belongs_to :schedule_chain
  belongs_to :location
  belongs_to :transport_type
  belongs_to :cell_carrier
  belongs_to :requested_region
end
